### PR TITLE
PR from mahajrod

### PR DESCRIPTION
**Pull request by mahajrod**
Hi @alejandrogzi,

This pull request includes couple of fixes to make postTOGA running (in my case it didn't work out of the box) and some additions to the readme.  Pull request includes several commits with detailed description of what was fixes inside each.

Also you may find informative a discussion here: https://github.com/hillerlab/TOGA/pull/106

Best regards,
Sergei

### CODE REVIEW

**Comment by alejandrogzi** [comment]
@mahajrod,

Thanks for your contributions! As I wrote earlier, I have not been able to focused 100% on posTOGA. The last week I made break changes in both bed converters (bed2gtf, bed2gff), this is why their functionality in posTOGA was broken (the argument parser logic changed). 

If you have more ideas on how to improve this project (desire functionality or implement other software) please let me know, it will be my pleasure!

Best,
Alejandro

**Comment by mahajrod** [comment]
Hi Alejandro,

I am happy that even with lack of time,  you still wish to continue to work on pisTOGA. I am happy to help you with it.
There couple things that could be added to the current implementation, but there is one thing I like very much in your pipeline: it is not overloaded and do not launch computationally heavy tools. I suggest to continue moving in this direction and retain the speed of posTOGA.

First improvement I suggest is to make pipeline more friendly to non-ensembl gene ids, by, for example, adding option for usage of common gene names. Also it makes sense to add gene list from different BUSCO databases and intersect them with evaluated annotation. Often it is interesting to see how complete your annotation compared to different datasets. For example, for carnivora species it might be carnivora_odb10, laurasitheria_odb10, mammalia_odb10 and vertebrata_odb10.
Fast intersection between gene list would be much better than just running BUSCO for all four databases. 

I have a specific interest in TOGA and posTOGA. Our team this year started building a reference genome assembly hub in Denmark (http://yggdrasil-genome.dk). And we need a fast and robust way to transfer and evaluate annotations from previously assembled genomes to allow our collaborators start post-assembly analyses immediately without waiting for ncbi annotations. So I will be happy to continue working with you.

Best regards,
Sergei

**Comment by alejandrogzi** [comment]
Sergei,

Such a motivation for me to hear that posTOGA fits your needs. Actually, this is the first feedback I got since I made it. The initial motivation was probably the extensive amount of post-processing steps I had to do to end with  a .gtf or a list of genes, among others. This idea led me to build probably most of my tools (e.g. bed2gtf, bed2gff).

Your proposal is something that I did not consider. In the README of this repo are some tasks/ideas I left as a reminder, running BUSCO was one of them; however, implement that would probably convert posTOGA to a very heavy pipeline. I found another tool called compleasm (initially called "mini-BUSCO"), that claimed a huge time reduction compared to BUSCO, this was my to-go choice. Intersecting BUSCO gene list is very clever, though, and a lot of time could be saved. 

I left posTOGA in "stand-by" because of time and other projects. The pending ideas waiting to be pushed included exon length calculation and this BUSCO thing. This, as funny as it sounds, led me to build another tool called [NOEL](https://github.com/alejandrogzi/noel).

I calculate that I will be working in slow mode until the last week of December due to some responsibilities (finishing my undergrad). After that all these features will be available. 

Yggdrasil seems a very interesting project, congratulations! If there is something else I can contribute with or room for other bioinformatics-related projects, let me know. I am very interested in collaborations, since I will be looking for PhD opportunities the next years! 

Regards,
Alejandro

**Comment by alejandrogzi** [comment]
Hi @mahajrod,

Since our last talk, some new changes have been made to postoga (following some of your recommendations). See the complete explanation here [TOGA/issues/135](https://github.com/hillerlab/TOGA/issues/135). Will be amazing to hear your feedback again! 

If any problem still persists please I encourage you to share some of your results (a .zip or .gz TOGA dir) to let me test them here.

Best,
Alejandro

**Pull request merged**
